apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-chat-config
  namespace: cloud-chat
data:
  NODE_ENV: "production"
  JWT_ACCESS_EXPIRES: "15m"
  JWT_REFRESH_EXPIRES: "7d"
  SMTP_HOST: "mailhog-service"
  SMTP_PORT: "1025"
  SMTP_FROM: "noreply@cloud-chat.app"
  FRONTEND_URL: "http://45.93.137.117:30080"
  PORT: "4000"
